// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXTBAa0x7uCKCCzYxZZ0825LDMODFVfwk',
    appId: '1:211133215594:web:054b71aae9a0306ad1eb13',
    messagingSenderId: '211133215594',
    projectId: 'makeuoft-2024',
    authDomain: 'makeuoft-2024.firebaseapp.com',
    databaseURL: 'https://makeuoft-2024-default-rtdb.firebaseio.com',
    storageBucket: 'makeuoft-2024.appspot.com',
    measurementId: 'G-Q1T4701EBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFMDKCvQU4-FGie6m451oYbJS-eYQ7Vg',
    appId: '1:211133215594:android:73bac8ce37aa28abd1eb13',
    messagingSenderId: '211133215594',
    projectId: 'makeuoft-2024',
    databaseURL: 'https://makeuoft-2024-default-rtdb.firebaseio.com/',
    storageBucket: 'makeuoft-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8sBhQB7_6NAei-6eaHjnlw03lDV5kqjM',
    appId: '1:211133215594:ios:e9955b2e87131387d1eb13',
    messagingSenderId: '211133215594',
    projectId: 'makeuoft-2024',
    databaseURL: 'https://makeuoft-2024-default-rtdb.firebaseio.com',
    storageBucket: 'makeuoft-2024.appspot.com',
    iosBundleId: 'com.example.alarmBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8sBhQB7_6NAei-6eaHjnlw03lDV5kqjM',
    appId: '1:211133215594:ios:474b0d506fd08d51d1eb13',
    messagingSenderId: '211133215594',
    projectId: 'makeuoft-2024',
    databaseURL: 'https://makeuoft-2024-default-rtdb.firebaseio.com',
    storageBucket: 'makeuoft-2024.appspot.com',
    iosBundleId: 'com.example.alarmBox.RunnerTests',
  );
}
